language: swift
osx_image: xcode9.4
xcode_project: ParselyDemo.xcodeproj # path to your xcodeproj folder
xcode_scheme: ParselyTrackerTests
xcode_destination: platform=iOS Simulator,OS=10.1,name=iPad Pro (9.7-inch)
before_install:
  - pod repo update
