language: swift
osx_image: xcode10.1
xcode_workspace: ParselyDemo.xcworkspace
xcode_scheme: ParselyTrackerTests
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X
before_install:
  - pod repo update
